fix(alert): prevent content from overflowing alert
vmware-clarity/core pull request #138
Opened 2022-08-04 18:05 UTC by ashleyryan

- flexbox has some quirks with overflow
- setting min-width: 0 prevents the content from overflowing

fixes #137

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Content with overflow-x: auto that would otherwise render a scrollbar in a small container are instead overflowing the alert

Issue Number: #137 

## What is the new behavior?

add min-width: 0 to allow content to be smaller than the implied width: https://css-tricks.com/flexbox-truncated-text/

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-08-04 19:02 UTC, kevinbuhmann requested changes

2022-08-04 19:02 UTC, kevinbuhmann commented on projects/core/src/alert/alert.element.spec.ts
> +          >
I think the `</pre>` tag should not be mangled/split like this. I'd but the entire closing tag on its own like like the opening tag.

2022-08-05 13:21 UTC, ashleyryan commented on projects/core/src/alert/alert.element.spec.ts
> +      expect(content.getBoundingClientRect().width).toBeLessThan(component.getBoundingClientRect().width);
I think it just waits for the component's rendering lifecycle to finish. It should probably be there to be safe. Updated

2022-08-05 13:22 UTC, ashleyryan commented on projects/core/src/alert/alert.element.spec.ts
> +            </pre
Prettier keeps mangling this, I cannot fix it

2022-08-05 21:00 UTC, steve-haar approved these changes

2022-08-15 14:24 UTC, merged

2022-08-15 14:24 UTC, kevinbuhmann approved these changes